[Wed Jan 10 21:30:12.542428 2024] [cgi:error] [pid 68248] [client ::1:50251] AH01215: Traceback (most recent call last):: /Users/grynch/Files/ITStep/Python-Uni/cgi/index.py
[Wed Jan 10 21:30:12.542951 2024] [cgi:error] [pid 68248] [client ::1:50251] AH01215:   File "/Users/grynch/Files/ITStep/Python-Uni/cgi/index.py", line 4, in <module>: /Users/grynch/Files/ITStep/Python-Uni/cgi/index.py
[Wed Jan 10 21:30:12.542970 2024] [cgi:error] [pid 68248] [client ::1:50251] AH01215:     import db_ini: /Users/grynch/Files/ITStep/Python-Uni/cgi/index.py
[Wed Jan 10 21:30:12.543009 2024] [cgi:error] [pid 68248] [client ::1:50251] AH01215: ModuleNotFoundError: No module named 'db_ini': /Users/grynch/Files/ITStep/Python-Uni/cgi/index.py
[Wed Jan 10 21:30:12.547026 2024] [cgi:error] [pid 68248] [client ::1:50251] End of script output before headers: index.py
